services:
  xml-json-converter:
    image: xml-json-converter:latest
    build: .
    container_name: xml-json-converter
    volumes:
      - ./input:/app/input        # Mounts input directory (for new XDP files)
      - ./reports:/app/reports    # Mounts reports directory (for logs)
      - ./output:/app/output      # Mounts output directory (for converted JSON files)
      - ./compare:/app/compare
    env_file:
      - .env
    command: ["python", "converter.py", "--watch", "--mapping", "/app/field_mappings.json"]
    restart: always
