apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "helm-chart.fullname" . }}-pvc"
spec:
  accessModes:
    - {{.Values.persistence.accessMode | quote}}
  resources:
    requests:
      storage: {{.Values.persistence.size}}
