{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "helm-chart.fullname" . }}-pvc"
  annotations: 
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  volumeMode: Filesystem
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
{{- end }}
