apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adze-dev-pvc
spec:
  accessModes:
    - { { .Values.persistence.accessMode } }
  resources:
    requests:
      storage: { { .Values.persistence.size } }
