name: CI Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - dev
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # - name: Run Python test suite
      #   run: |
      #     pytest tests/test_converters.py --maxfail=2 --disable-warnings -v

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Git SHA for version tagging
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            jiminaot/xml-json-converter:latest
            jiminaot/xml-json-converter:${{ env.SHORT_SHA }}
          platforms: linux/amd64

      - name: Verify Docker image
        run: docker pull jiminaot/xml-json-converter:latest

  helm-lint:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Lint Helm charts
        run: helm lint helm-chart/

      - name: Render Helm templates using values-dev.yaml
        run: |
          helm template adze-dev helm-chart/ -f helm-chart/values-dev.yaml --debug
