name: CI Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Run unit tests
      #   run: |
      #     pip install pytest
      #     pytest

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint Helm charts
        run: |
          helm lint helm-chart/
