name: CI Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Uncomment if you have unit tests
      # - name: Run unit tests
      #   run: |
      #     pip install pytest
      #     pytest

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Git SHA for Versioning
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            jiminaot/xml-json-converter:latest
            jiminaot/xml-json-converter:${{ env.SHORT_SHA }}
          platforms: linux/amd64

      - name: Verify Image on Docker Hub
        run: docker pull jiminaot/xml-json-converter:latest               

  helm:
    runs-on: ubuntu-latest
    needs: lint  # Runs after lint job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Lint Helm charts
        run: |
          helm lint helm-chart/

      - name: Render Helm templates with values-dev.yaml
        run: |
          helm template adze-dev helm-chart/ -f helm-chart/values-dev.yaml --debug

