name: Lint and Test

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-test:
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest, macos-latest]
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      # - name: Run Local Tests
      #   run: pytest tests/unit/ --cov=xml_converter_class --cov-report=term

      - name: Build Docker Image
        run: |
          docker build -t xml-json-converter .

      # - name: Run Containerized Tests
      #   run: |
      #     docker run --rm xml-json-converter pytest tests/unit/

  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Lint Helm Charts
        run: helm lint ./helm-chart/